from pathlib import Path
import subprocess, struct, re, json, hashlib

w = Path(__file__).resolve().parents[1]
g = w / 'glue/rexglue-sdk-main/src/graphics/gta4_native'
import argparse
parser = argparse.ArgumentParser(description="Compile and embed the presentation fragment shaders")
parser.add_argument('--compiler', required=True, type=Path)
parser.add_argument('--output-dir', required=True, type=Path)
args = parser.parse_args()
out, compiler = args.output_dir.resolve(), args.compiler.resolve()
out.mkdir(parents=True, exist_ok=True)
assets = w / 'LibertyRecompLib/postfx/smaa'
manifest = {}
for name, shader in [('smaa_present_ps', g / 'smaa/smaa_present_ps.glsl'),
                     ('smaa_neighborhood_ps', g / 'smaa/smaa_neighborhood_ps.glsl'),
                     ('hdr_present_ps', g / 'hdr_present_ps.glsl')]:
    binary = out / (name + '.spv')
    subprocess.run([str(compiler), '-V', '--target-env', 'vulkan1.1',
                    '-I' + str(assets), '-DSMAA_PRESET_HIGH=1', '-S', 'frag',
                    str(shader), '-o', str(binary)], check=True)
    words = struct.unpack('<' + 'I' * (len(binary.read_bytes()) // 4), binary.read_bytes())
    data = '\n'.join('    ' + ', '.join(f'0x{x:08X}' for x in words[i:i+8]) + ','
                     for i in range(0, len(words), 8)) + '\n'
    if name == 'smaa_present_ps':
        (g / 'smaa/smaa_present_ps.inc').write_text(
            '// Generated by tools/compile_graphics_presentation.py.\n'
            'inline constexpr uint32_t smaa_present_ps[] = {\n' + data + '};\n')
    elif name == 'smaa_neighborhood_ps':
        target = g / 'smaa/smaa_shaders.inc'
        text, count = re.subn(r'inline constexpr uint32_t smaa_neighborhood_ps\[\] = \{.*?\};',
                             'inline constexpr uint32_t smaa_neighborhood_ps[] = {\n' + data + '};',
                             target.read_text(), flags=re.S)
        assert count == 1
        target.write_text(text)
    else:
        (g / 'hdr_present_ps.inc').write_text(data)
    manifest[name] = {'bytes': binary.stat().st_size,
                      'sha256': hashlib.sha256(binary.read_bytes()).hexdigest()}
(out / 'SHADERS.json').write_text(json.dumps(manifest, indent=2) + '\n')
